update go and alpine versions
fabiolb/fabio pull request #868
Opened 2022-04-07 06:48 UTC by Netlims

There are many CVEs on the current alpine and golang version.
I have updated both and tested it on my local environment, it seems to have no effect on Fabio's functionality.

2022-04-07 06:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fabiolb/fabio?pullRequest=868) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fabiolb/fabio?pullRequest=868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fabiolb/fabio?pullRequest=868) it.</sub>

2022-04-08 18:44 UTC, nathanejohnson commented
This looks good.  If you sign the CLA I'll merge this ASAP.

2022-04-08 20:16 UTC, nathanejohnson requested changes

2022-04-08 20:16 UTC, nathanejohnson commented on Dockerfile
This should be 

    FROM golang:1.18-alpine3.15 AS build

we should have always been specifying the alpine version so musl versions would match.

2022-04-09 17:37 UTC, Netlims commented
@nathanejohnson Good catch. I pushed the change and signed the CLA

2022-04-09 22:57 UTC, nathanejohnson approved these changes

2022-04-09 22:57 UTC, merged