Update and try fix GH Pages publish action.
fabiolb/fabio pull request #953
Opened 2024-09-06 03:38 UTC by tristanmorgan

from the latest version of the [gh-pages docs](https://github.com/peaceiris/actions-gh-pages/blob/main/README.md#%EF%B8%8F-set-runners-access-token-github_token) it should use GITHUB_TOKEN to authenticate...

2024-09-08 23:30 UTC, tristanmorgan commented
@aaronhurt tested on my fork [see](https://github.com/tristanmorgan/fabio/actions/runs/10763933663/job/29846039987)

2024-09-09 02:47 UTC, dcarbone requested changes
One small change, otherwise lgtm

2024-09-09 02:47 UTC, dcarbone commented on .github/workflows/github-pages.yml
> +      - uses: actions/checkout@master
Change this to `@v4`, please

2024-09-09 03:04 UTC, nathanejohnson requested changes
it looks like there are whitespace issues with this commit as well, the file uses spaces for indent

2024-09-09 03:45 UTC, tristanmorgan commented
I pinned the actions/checkout version to v4, and dropped the formatting commit.

2024-09-09 14:07 UTC, nathanejohnson approved these changes

2024-09-09 16:54 UTC, dcarbone approved these changes

2024-09-09 22:16 UTC, merged